In [26]:
import tensorflow as tf
import numpy as np

In [2]:
#matrix
#create a graph
sess = tf.Session()

In [3]:
#identity matrix
id_mat = tf.diag([1.0,1.0,1.0])
sess.run(id_mat)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [5]:
#2*3 random norm matrix

A = tf.truncated_normal([2,3])
sess.run(A)

array([[-0.7621303 , -0.23353502, -0.47499225],
       [ 0.6220413 , -0.02735015,  0.5197806 ]], dtype=float32)

In [6]:
#2*3 constant matrix

B = tf.fill([2,3],5.0)
sess.run(B)

array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)

In [7]:
#3*2 random uniform matrix
C = tf.random_uniform([3,2])
sess.run(C)

array([[0.93289423, 0.13928688],
       [0.26485205, 0.39993644],
       [0.01669991, 0.8311732 ]], dtype=float32)

In [15]:
#create matrix from numpy array 
D= tf.convert_to_tensor(np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[6.0,7.0,8.0]]))
sess.run(D)

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]])

In [10]:
#matrix addition\ substraction
print(sess.run(A+B))
print(sess.run(A-B))

[[4.7672644 4.928859  5.387773 ]
 [6.527652  4.5702167 5.149188 ]]
[[-4.589452  -6.3439655 -4.1770205]
 [-4.1953583 -6.9855695 -5.4097   ]]


In [11]:
#matrix multiplication

sess.run(tf.matmul(B,id_mat))

array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)

In [13]:
#matrix transpose
sess.run(tf.transpose(C))

array([[0.62507796, 0.31981957, 0.42574966],
       [0.1685834 , 0.72899365, 0.7394841 ]], dtype=float32)

In [16]:
#matrx determinant

sess.run(tf.matrix_determinant(D))

-3.885780586188069e-15

In [17]:
#matrx inverse

sess.run(tf.matrix_inverse(D))

array([[ 5.14697100e+14, -1.28674275e+15,  7.72045650e+14],
       [-1.02939420e+15,  2.57348550e+15, -1.54409130e+15],
       [ 5.14697100e+14, -1.28674275e+15,  7.72045650e+14]])

In [18]:
#cholesky decomposition
sess.run(tf.cholesky(id_mat))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [19]:
#eig value & vector

sess.run(tf.self_adjoint_eig(D))

(array([-2.4463372 , -0.45941254, 16.90574974]),
 array([[ 0.86525321,  0.28571346,  0.41195231],
        [ 0.0064518 , -0.82798841,  0.56070809],
        [-0.50129359,  0.48249664,  0.718263  ]]))

In [21]:
#constant & variables & placeholder
"""constant--tf.constant(value,dtype=None,shape=None,name='Const',verify_shape=False,)"""
conscalar = tf.constant(100)
convector = tf.constant([1,2,3])
conmatrix = tf.constant([[1,2,3],[4,5,6],[6,7,8]])
print(sess.run(conscalar),">>>", sess.run(convector), ">>>>", sess.run(conmatrix))

100 >>> [1 2 3] >>>> [[1 2 3]
 [4 5 6]
 [6 7 8]]


In [27]:
con1 = tf.constant(3.0,tf.float32)
con2 = tf.constant(4.0)
print(sess.run([con1,con2]))

[3.0, 4.0]


In [32]:
con3 = con1*con2
print(sess.run(con3))

con4 = tf.constant(10, dtype=tf.float32, shape=[3,3])
sess.run(con4)

12.0


array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]], dtype=float32)

In [34]:
#placeholder 
""" placeholder---tf.placeholder(dtype, shape=None, name=None)"""
"""placeholder is used to call the data from outside"""
a= 2
b= 3
pla = tf.placeholder(dtype=tf.float32, shape=(a,b))
pla1 = tf.add(a,b)
data = np.random.rand(a,b)
sess.run(pla1, feed_dict={pla:data})


5

In [35]:
pla2 = tf.placeholder(dtype=tf.float32)
pla3 = tf.placeholder(dtype=tf.float32)

add_pla = tf.add(pla2,pla3)
sess.run(add_pla, feed_dict={pla2:[10,12], pla3:[23,25]})

array([33., 37.], dtype=float32)

In [36]:
# Variables
""" variables used for update the value"""
"""w = tf.Variable(<initial-value>, name=<optional-name>)"""
#var = tf.Variable([0.01])

'w = tf.Variable(<initial-value>, name=<optional-name>)'